// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/services.go

// Package mock_services is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	services "github.com/marioTiara/todolistapi/internal/app/services"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FileService mocks base method.
func (m *MockService) FileService() services.FileService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileService")
	ret0, _ := ret[0].(services.FileService)
	return ret0
}

// FileService indicates an expected call of FileService.
func (mr *MockServiceMockRecorder) FileService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileService", reflect.TypeOf((*MockService)(nil).FileService))
}

// TaskService mocks base method.
func (m *MockService) TaskService() services.TaskService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskService")
	ret0, _ := ret[0].(services.TaskService)
	return ret0
}

// TaskService indicates an expected call of TaskService.
func (mr *MockServiceMockRecorder) TaskService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskService", reflect.TypeOf((*MockService)(nil).TaskService))
}
